# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5489:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: root
      POSTGRES_DB: multikart

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080